trigger:
  batch: true
  branches:
    include:
      - testen
      - az-acceptance
      - main
      - production-release-v*
pr:
  autoCancel: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/pipeline-fe

parameters:
  - name: pipelineAction
    type: string
    default: btd
    values:
      - btd
      - updateAppSettings

  - name: dtapName
    type: string
    default: t
    values:
      - t
      - a
      - p

  - name: btdBuild
    type: boolean
    default: true
  - name: btdTest
    type: boolean
    default: true
  - name: btdDeploy
    type: boolean
    default: true

variables:
  - name: btdBuild
    value: ${{ parameters.btdBuild }}
  - name: btdTest
    value: ${{ parameters.btdTest }}
  - name: btdDeploy
    value: ${{ parameters.btdDeploy }}

  - ${{ if or(eq(variables['Build.SourceBranchName'], 'testen'), eq(variables['Build.Reason'], 'PullRequest')) }}:
      - name: dtapName
        value: t
  - ${{ if or(eq(variables['Build.SourceBranchName'], 'az-acceptance'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      - name: dtapName
        value: a
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - name: btdDeploy
        value: false
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - name: btdDeploy
        value: ${{ parameters.btdDeploy }}
  - ${{ if ne(parameters.dtapName, 'none') }}:
      - name: dtapName
        value: ${{ parameters.dtapName }}

  - ${{ if and(contains(variables['Build.SourceBranchName'], 'production-release'), eq(parameters.pipelineAction, 'btd')) }}:
      - name: dtapName
        value: p
      - name: btdBuild
        value: true
      - name: btdTest
        value: true
      - name: btdDeploy
        value: true

  - ${{ if eq(parameters.pipelineAction, 'updateAppSettings') }}:
      - name: btdBuild
        value: false
      - name: btdTest
        value: false
      - name: btdDeploy
        value: false

jobs:
  - template: pipelines/jobs/apps/btd-koppel-api.yaml@MamsInfra
    parameters:
      appServiceShortName: vergunningen
      dtapName: ${{ variables.dtapName }}
      btdBuild: ${{ variables.btdBuild }}
      btdTest: ${{ variables.btdTest }}
      btdDeploy: ${{ variables.btdDeploy }}
      pipelineAction: ${{ parameters.pipelineAction }}
      aquaScan: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
