trigger:
  batch: true
  branches:
    include:
      - testen
      - az-acceptance
      - main
      - production-release-v*
pr:
  autoCancel: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/main

parameters:
  - name: dtapName
    displayName: Test or Acc
    type: string
    default: t
    values:
      - t
      - a

  - name: btdBuild
    type: boolean
    default: true
  - name: btdTest
    type: boolean
    default: true
  - name: btdDeploy
    type: boolean
    default: true

variables:
  - name: btdBuild
    value: ${{ parameters.btdBuild }}
  - name: btdTest
    value: ${{ parameters.btdTest }}
  - name: btdDeploy
    value: ${{ parameters.btdDeploy }}
  - name: dtapName
    value: ${{ parameters.dtapName }}

  - ${{ if or(eq(variables['Build.SourceBranchName'], 'testen'), eq(variables['Build.Reason'], 'PullRequest')) }}:
      - name: dtapName
        value: t
  - ${{ if or(eq(variables['Build.SourceBranchName'], 'az-acceptance'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      - name: dtapName
        value: a
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - name: btdDeploy
        value: false

  - ${{ if contains(variables['Build.SourceBranchName'], 'production-release') }}:
      - name: btdBuild
        value: true
      - name: btdTest
        value: true
      - name: btdDeploy
        value: true
      - name: dtapName
        value: p

jobs:
  - template: pipelines/jobs/apps/btd-koppel-api.yaml@MamsInfra
    parameters:
      appServiceShortName: vergunningen
      dtapName: ${{ variables.dtapName }}
      btdBuild: ${{ variables.btdBuild }}
      btdTest: ${{ variables.btdTest }}
      btdDeploy: ${{ variables.btdDeploy }}
