trigger:
  batch: true
  branches:
    include:
      - ontwikkelen
      - testen
pr:
  autoCancel: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/pipeline-fe

parameters:
  - name: btdBuild
    type: boolean
    default: true
  - name: btdTest
    type: boolean
    default: true
  - name: btdDeploy
    type: boolean
    default: true
  - name: dtapName
    type: string
    default: none
    values:
      - none
      - o
      - t
      # - a
      # - p
  - name: updateAppSettings
    type: boolean
    default: false

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'ontwikkelen') }}:
      - name: dtapName
        value: o
  - ${{ if and(or(eq(variables['Build.SourceBranchName'], 'testen'), eq(variables['Build.Reason'], 'PullRequest')), eq(parameters.dtapName, 'none')) }}:
      - name: dtapName
        value: t
  - ${{ if ne(parameters.dtapName, 'none') }}:
      - name: dtapName
        value: ${{ parameters.dtapName }}

jobs:
  - template: pipelines/jobs/apps/btd-koppel-api.yaml@MamsInfra
    parameters:
      appServiceShortName: vergunningen
      dtapName: ${{ variables.dtapName }}
      btdBuild: ${{ parameters.btdBuild }}
      btdTest: ${{ parameters.btdTest }}
      btdDeploy: ${{ parameters.btdDeploy }}
      updateAppSettings: ${{ parameters.updateAppSettings }}
      aquaScan: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
