version: "3.0"

services:
  api:
    build: ./app
    ports:
      - 8000:5000
    environment:
      - UWSGI_HTTP=0.0.0.0:5000
      - UWSGI_STATS=0.0.0.0:9191
      - UWSGI_MAX_REQUESTS=5000
      - UWSGI_MASTER=1
      - UWSGI_WORKERS=4
      - UWSGI_CALLABLE=app
      - UWSGI_MODULE=api.server
      - UWSGI_BUFFER_SIZE=32768
      - UWSGI_LOGTO=uwsgi.log
